### 1. NumPy

> **In one line:** NumPy is the foundational Python library for efficient numerical computing, providing high-performance N-dimensional array manipulation, broadcasting, and linear algebra routines essential for machine learning.

#### Must Learn

**Basics**
* **Arrays (`ndarray`)**
* **Attributes:**
  * `shape` — Dimensions of the array
  * `ndim` — Number of array axes
  * `size` — Total number of elements
  * `dtype` — Data type of elements
* **Indexing & Slicing**

**Array Operations**
* Addition / subtraction / multiplication
* Element-wise operations
* Broadcasting
* Comparison operations
* Boolean masking

**Important Functions**
* `np.array()` — Create an array
* `np.zeros()` — Array filled with zeros
* `np.ones()` — Array filled with ones
* `np.arange()` — Array with evenly spaced values within a given range
* `np.linspace()` — Evenly spaced numbers over a specified interval
* `np.reshape()` — Change array dimensions without altering data
* `ndarray.flatten()` — Collapse array into a 1D copy
* `np.concatenate()` — Join arrays along an existing axis
* `np.vstack()` — Stack arrays vertically
* `np.hstack()` — Stack arrays horizontally

**Statistics**
* `np.mean()` — Arithmetic mean
* `np.median()` — Median value
* `np.std()` — Standard deviation
* `np.var()` — Variance
* `np.min()` / `np.max()` — Minimum and maximum values
* `np.sum()` — Sum of elements

**Linear Algebra (Very Important)**
* **Core Concepts:**
  * Dot product
  * Matrix multiplication
  * Transpose
  * Inverse
  * Eigenvalues & eigenvectors
* **Key Functions:**
  * `np.dot()` — Dot product of two arrays
  * `np.matmul()` — Matrix product of two arrays
  * `np.linalg` — Submodule for matrix decompositions, inverses, and eigenvalues

In [1]:
import numpy as np

# Basic

In [6]:
# A standard 1D array
arr = np.array([10, 20, 30, 40, 50])
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
# Create a 2D grid (2 rows, 3 columns)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

In [17]:
print(f"Number of Dimension:    {matrix.ndim}")
print(f"Dimension Layout:       {matrix.shape}")
print(f"Total Element:          {matrix.size}")
print(f"Data Type:              {matrix.dtype}")

Number of Dimension:    2
Dimension Layout:       (2, 3)
Total Element:          6
Data Type:              int64


# Indexing (Grabbing a Single Item)
NumPy uses zero-based indexing (`0` is the first element, `-1` is the last).

In [18]:
# 1D Indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"First item: {arr_1d[0]}")
print(f"Last item:  {arr_1d[-1]}")

First item: 10
Last item:  50


In [ ]:
# 2D Indexing [row, column]
arr_2d = np.array([
    [1, 2, 3],  # Row 0 
    [4, 5, 6],  # Row 1
    [7, 8, 9]   # Row 3
])
print(f"First row First col:    {arr_2d[0, 0]}")
print(f"Last row Last col:      {arr_2d[-1, -1]}")


First row First col:    1
Last row Last col:      9


## Slicing (Grabbing a Sub-range)
Slicing syntax follows `start` : `stop` : `step` (where `stop` is non-inclusive).

In [26]:
# 1D Slicing
arr_sl_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"Index 2 up to, but not including, 6:    {arr_sl_1d[2:6]}")
print(f"Start to index 3:                       {arr_sl_1d[:4]}")
print(f"Index 6 to end:                         {arr_sl_1d[6:]}")
print(f"Every 2nd item:                         {arr_sl_1d[::2]}")
print(f"Reverse:                                {arr_sl_1d[::-1]}")

Index 2 up to, but not including, 6:    [2 3 4 5]
Start to index 3:                       [0 1 2 3]
Index 6 to end:                         [6 7 8 9]
Every 2nd item:                         [0 2 4 6 8]
Reverse:                                [9 8 7 6 5 4 3 2 1 0]


In [31]:
arr_sl_2d = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

print("Grab the entire first row")
print(arr_sl_2d[0, :])

print("\nGrab the entire second column")
print(arr_sl_2d[:, 1])

print("\nGrab a 2x2 sub-grid (rows 1-2, cols 2-3)")
print(arr_sl_2d[1:3, 2:4])

Grab the entire first row
[11 12 13 14]

Grab the entire second column
[12 22 32 42]

Grab a 2x2 sub-grid (rows 1-2, cols 2-3)
[[23 24]
 [33 34]]


# Element-Wise Operations & Basic Arithmetic
In Python lists, adding two lists joins them (`[1] + [2] = [1, 2]`). In NumPy, standard operators (`+`, `-`, `*`, `/`, `**`) apply element-by-element.

***Note: For element-wise operations with two arrays, their shapes must either match exactly or follow broadcasting rules.***

In [32]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print(f"Addition:       {a+b}")
print(f"Subtraction:    {a-b}")
print(f"Multiplication: {a*b}")
print(f"Division:       {a/b}")
print(f"Power:          {b**2}")

Addition:       [11 22 33 44 55]
Subtraction:    [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division:       [10. 10. 10. 10. 10.]
Power:          [ 1  4  9 16 25]


# Broadcasting
Broadcasting lets NumPy perform arithmetic on arrays of **different shapes** without creating unnecessary copies of data.

**The Two Broadcasting Compatibility Rules:**
1. The dimensions are equal, **OR**
2. One of the dimensions is `1`.

In [ ]:
# Case A: Array and a Scalar (Single Number)
scores = np.array([80, 90, 95])

print("Add 5 bonus points to every score")
print(scores + 5)

Add 5 bonus points to every score
[ 85  95 100]


In [47]:
# Case B: 2D Matrix and 1D Row
matrix_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
row = np.array([10, 20, 30]) # Shape (3,)

print("The row is added to row 0, row 1, and row 2")
print(matrix_2d + row)

The row is added to row 0, row 1, and row 2
[[11 22 33]
 [14 25 36]
 [17 28 39]]


## Comparison Operations

Applying comparison operators (`>`, `<`, `>=`, `<=`, `==`, `!=`) evaluates every element individually and returns an array of booleans (`True` or `False`).

In [49]:
ages = np.array([15, 22, 18, 30, 12, 45])

print(f"Check which elements are adult age")
print(ages >= 18)

Check which elements are adult age
[False  True  True  True False  True]


# Boolean Masking (Filtering)

Boolean masking means using an array of `True`/`False` values to index and filter another array. Only the elements corresponding to `True` are retained.

In [50]:
ages_1d = np.array([15, 22, 18, 30, 12, 45])

print("Filter only values >= 18")
print(ages_1d[ages_1d >= 18])

Filter only values >= 18
[22 18 30 45]


**Multiple Conditions**

Use bitwise operators:

- `&` for AND
- `|` for OR
- `~` for NOT

In [53]:
temps = np.array([18, 25, 32, 40, 15, 28])

print("Keep temperature between 20 to 35")
print(temps[(temps >= 20) & (temps <= 35)])

print("\nAssign value based on a condition (Replace outliers)")
temps[temps > 35] = 35
print(temps)

Keep temperature between 20 to 35
[25 32 28]

Assign value based on a condition (Replace outliers)
[18 25 32 35 15 28]


`np.array()` — Convert existing data

Turns standard Python lists or tuples into an `ndarray`.

In [ ]:
# 1D array
nums = np.array([1, 2, 3])

# 2D array from nested lists
grid = np.array([[1, 2], [3, 4]])

`np.zeros()` — Fill with zeros

Creates an array filled entirely with `0.0`. Pass the desired shape as an integer or tuple: `(rows, columns)`.

In [56]:
print("1D array of 4 zeros")
print(np.zeros(4))

print("\n2D grid: 2 rows, 3 columns")
print(np.zeros((2, 3)))

1D array of 4 zeros
[0. 0. 0. 0.]

2D grid: 2 rows, 3 columns
[[0. 0. 0.]
 [0. 0. 0.]]


`np.ones()` — Fill with ones

Identical to `np.zeros()`, but fills slots with `1.0`.

In [58]:
print(np.ones((2, 2)))

[[1. 1.]
 [1. 1.]]


`np.arange()` — Spaced by step size

Works like Python's `range(start, stop, step)`. The `stop` value is excluded.

*Rule of thumb:* Use `arange` when you care about the step size; use `linspace` when you care about the exact count of points.

In [62]:
print("np.arange(start, stop, step)")
print(np.arange(1, 10, 1))

print("\nFloating point steps work too")
print(np.arange(0, 1, 0.2))

np.arange(start, stop, step)
[1 2 3 4 5 6 7 8 9]

Floating point steps work too
[0.  0.2 0.4 0.6 0.8]


`np.linspace()` — Spaced by number of samples

Generates an exact count of evenly spaced values over an interval. Unlike `arange`, both endpoints are included by default.

In [66]:
# np.linspace(start, stop, num_points)
# Generate exactly 5 evenly spaced numbers between 0 and 100
print(np.linspace(0, 100, 6))

[  0.  20.  40.  60.  80. 100.]


# Reshaping & Flattening

These tools restructure the layout of array elements without modifying the underlying values.

`np.reshape()` — Change the dimensions

Changes the arrangement of rows and columns. The total number of elements ($rows \times cols$) must match the original count.

In [80]:
arr = np.arange(1, 7)
print("Original array")
print(arr)

reshape = arr.reshape(2, 3)
print("\nReshape to 2 rows and 3 cols")
print(reshape)

print("\nTrick: Use -1 to let Numpy auto-calculate one dimension")
print(arr.reshape(3, -1))

Original array
[1 2 3 4 5 6]

Reshape to 2 rows and 3 cols
[[1 2 3]
 [4 5 6]]

Trick: Use -1 to let Numpy auto-calculate one dimension
[[1 2]
 [3 4]
 [5 6]]


`.flatten()` — Collapse to 1D

Converts any multi-dimensional array into a flat 1D array.

*Note:* `flatten()` is called as an array method (`arr.flatten()`), not `np.flatten(arr)`. It always returns an independent copy.

In [81]:
matrix = np.array([
    [10, 20],
    [30, 40]
])
flat = matrix.flatten()
print(flat)

[10 20 30 40]


# Combining & Stacking Arrays

These functions join multiple arrays together.

`np.concatenate()` — General-purpose joining

Joins arrays along an existing axis. Default is `axis=0` (vertical/row-wise).

In [86]:
a = np.array([
    [10, 20],
    [30, 40]
])
b = np.array([
    [50, 60],
    [70, 80],
])

print("Stack along rows (axis=0)")
print(np.concatenate((a, b), axis=0))

print("\nStack along columns (axis=1)")
print(np.concatenate((a, b), axis=1))

Stack along rows (axis=0)
[[10 20]
 [30 40]
 [50 60]
 [70 80]]

Stack along columns (axis=1)
[[10 20 50 60]
 [30 40 70 80]]


`np.vstack()` — Vertical stack

Stacks arrays **on top of each other** (row-by-row). They must share the same number of columns.

In [92]:
row1 = np.array([1, 2, 3])
row2 = np.array([4, 5, 6])

print(np.vstack((row1, row2)))

[[1 2 3]
 [4 5 6]]


`np.hstack()` — Horizontal stack

Stacks arrays **side-by-side** (column-by-column). They must share the same number of rows.

In [93]:
col1 = np.array([
    [1],
    [2],
    [3]
])
col2 = np.array([
    [4],
    [5],
    [6]
])
print(np.hstack((col1, col2)))

[[1 4]
 [2 5]
 [3 6]]


Statistical functions in NumPy summarize large datasets in a single line of code. The key concept to understand first is the `axis` parameter:

- **No axis specified:** Computes the statistic over the entire array (collapses everything into a single scalar).
- `axis=0`**:** Operates **down the columns** (collapses rows; result has length equal to columns).
- `axis=1`**:** Operates **across the rows** (collapses columns; result has length equal to rows).

# 1. The Core Functions

In [95]:
scores = np.array([10, 20, 30, 40, 50, 100])
print(scores)

[ 10  20  30  40  50 100]


`np.sum()` — Total Sum

Adds all values together.

In [96]:
print(np.sum(scores))

250


`np.mean()` — Arithmetic Average

Calculates $\frac{\text{sum of all elements}}{\text{number of elements}}$.

In [97]:
print(np.mean(scores))

41.666666666666664


`np.median()` — Middle Value

Sorts the numbers and picks the center value (or averages the middle two). Unlike np.mean, it is resistant to extreme outliers.

In [99]:
# Sorted: [10, 20, 30, 40, 50, 100] -> Middle two are 30 and 40
print(np.median(scores))

35.0


`np.var()` — Variance

Measures how spread out numbers are around the mean (average of squared differences from the mean).

In [102]:
print(np.var(scores))

847.2222222222222


`np.std()` — Standard Deviation

The square root of variance ($\sqrt{\text{variance}}$). It measures spread in the original unit of your data.

In [103]:
print(np.std(scores))

29.1070819942883


`np.min()` & `np.max()`— Extrema

Returns the smallest and largest values in the array.

In [104]:
print(np.min(scores))
print(np.max(scores))

10
100


# 2. Using axis in 2D Arrays (Matrices)

In machine learning, rows typically represent samples (e.g., individual students) and columns represent **features** (e.g., test scores in Math, Science, English).

In [106]:
# Rows: Students | Columns: [Maths, Science, English]
grades = np.array([
    [80, 90, 70],   # Student 1
    [60, 50, 95],   # Student 1
    [90, 85, 80]    # Student 1
])
print(grades)

[[80 90 70]
 [60 50 95]
 [90 85 80]]


**Global Calculation (No axis)**

In [108]:
# Average of all 9 test scores combined
print(np.mean(grades))

77.77777777777777


**Column-wise**: `axis=0` (Collapse rows)

Use this to find the average or min/max **per subject**:

In [111]:
print("Average score for Maths, Science and English")
print(np.mean(grades, axis=0))

print("\nHight score recorded in each subject")
print(np.max(grades, axis=0))

Average score for Maths, Science and English
[76.66666667 75.         81.66666667]

Hight score recorded in each subject
[90 90 95]


**Row-wise**: `axis=1` (Collapse columns)

Use this to find the average or total **per student**:

In [112]:
print("Final average for student 1, student 2 and student 3")
print(np.mean(grades, axis=1))

print("Total points earning by each student")
print(np.sum(grades, axis=1))

Final average for student 1, student 2 and student 3
[80.         68.33333333 85.        ]
Total points earning by each student
[240 205 255]


## Liner Algebra

Linear algebra is the mathematical engine behind neural networks, computer vision, and recommendation systems. Machine learning models treat inputs as vectors and layer weights as matrices.

**1. Dot ProductThe** 

dot product multiplies corresponding elements of two 1D vectors and sums the results, producing a single number (scalar):
$$\mathbf{a} \cdot \mathbf{b} = \sum a_i b_i$$
In ML, this represents a weighted sum (e.g., inputs multiplied by weights).

In [113]:
# Inputs: [Hours studies, Practice tests taken]
x = np.array([3, 2])

# Model weight
w = np.array([10, 5])

# Dot product: (3 * 10) + (2 * 5) = 30 + 10 = 40
score = np.dot(x, w)
print(score)

40


**2. Matrix Multiplication (`np.matmul` or `@`)**

Matrix multiplication applies dot products across rows of matrix $A$ and columns of matrix $B$.

- Shape Rule: The inner dimensions must match:

$$(M \times K) \times (K \times N) \rightarrow (M \times N)$$

`*` vs `np.dot` / `@`:

- `A * B` performs **element-wise multiplication** (shapes must match or broadcast).

- `A @ B` performs **matrix multiplication** (rows dot columns).

In [116]:
# A: 2 samples, 3 features (Shape: 2 x 3) 
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# B: 3 features, 2 output neurons (Shape: 3 x 2)
B = np.array([
    [7, 8],
    [9, 1],
    [2, 3]
])

# Method 1: np.matmul()
result = np.matmul(A, B)

# Method 2: The '@' operator (standard Python syntax for matmul)
result_operator = A @ B

print(result)

[[31 19]
 [85 55]]


**3. Transpose `(.T)`**

Transposing flips a matrix over its diagonal, swapping rows and columns. An $(M \times N)$ matrix becomes $(N \times M)$.

In ML, transpose is used constantly to align matrix dimensions for multiplication.

In [122]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Shape: {A.shape}")

# Transpose using .T attribute
A_transposed = A.T
print("\nTranspose")
print(A_transposed)
print(f"Shape: {A_transposed.shape}")

Shape: (2, 3)

Transpose
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


**4. Matrix Inverse (`np.linalg.inv()`)**

The inverse of a square matrix $A$ is denoted $A^{-1}$. Multiplying a matrix by its inverse yields the Identity Matrix ($I$), which acts like the number 1 for matrices:

$$A \cdot A^{-1} = I$$

In ML, inverses appear in exact analytical solutions, such as the Normal Equation for Linear Regression.

*Note: Only square matrices with a non-zero determinant have an inverse. Non-invertible matrices are called singular.*

In [124]:
A = np.array([
    [4, 7],
    [2, 6]
])

# Compute inverse
A_inv = np.linalg.inv(A)
print(A_inv)

# Verification: A @ A_inv should give Identity matrix [[1, 0], [0, 1]]
print(np.round(A @ A_inv))

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1. -0.]
 [ 0.  1.]]


**5. Eigenvalues and Eigenvectors (`np.linalg.eig()`)**

When a matrix transforms space, it usually rotates and stretches vectors. Eigenvectors are special vectors whose direction does not change during the transformation—they are only scaled by a factor called the eigenvalue ($\lambda$):

$$A \mathbf{v} = \lambda \mathbf{v}$$

- **Why it matters in ML**: Principal Component Analysis (PCA) relies on eigenvectors of covariance matrices to find the axes of maximum variance and compress data.

In [125]:
A = np.array([
    [2, 0],
    [0, 3]
])

# Compute eigenvalues and right eigenvecotr
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues")
print(eigenvalues)

print("\nEigenvecotrs")
print(eigenvectors)

Eigenvalues
[2.+0.j 3.+0.j]

Eigenvecotrs
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
