# Linear Algebra

In [1]:
import numpy as np

## What is Scalar?

In linear algebra and machine learning, a **scalar** is simply a single number. Unlike vectors or matrices that hold multiple values, a scalar represents a single quantity with magnitude (size) but no direction.

- Typically drawn from the set of real numbers, denoted mathematically as $s \in \mathbb{R}$.
- Examples include everyday values like integers, floating-point numbers, or constants (e.g., $4$, $-1.5$, or $3.14$).

**Notation and Representation**

Standard mathematical conventions help distinguish scalars from multi-valued structures:

- **Scalars** are usually written as lowercase, italicized letters (e.g., $a$, $x$, $c$).
- **Vectors** are typically represented as lowercase bold letters (e.g., $\mathbf{v}$), and matrices as uppercase bold letters (e.g., $\mathbf{W}$).
- In programming, a scalar translates directly to a primitive data type like a `float` or an `int` (such as a single variable holding a learning rate).

**Role of Scalars in Machine Learning**

Scalars are the fundamental building blocks of almost every machine learning algorithm:

- **Model Parameters**: Individual weights and biases within neural network layers are often scalars that get updated during training.
- **Hyperparameters**: Configuration values like the learning rate ($\alpha$), dropout rate, or regularization strength are scalar values set before training begins.
- **Scalar Operations**: You can perform arithmetic operations (addition, subtraction, multiplication, division) between a scalar and a scalar, or use scalar multiplication to scale an entire vector or matrix by a constant factor (e.g., scaling vector $\mathbf{v}$ by scalar $c$ yields $c\mathbf{v}$).

In NumPy, a scalar can be represented either as a standard Python number or explicitly as a **0-dimensional array** (`ndim == 0`), which is how NumPy treats single numeric values in matrix and vector operations.

In [ ]:
# 1. Creating explicit Numpy scalar with specific data types
learning_rate = np.float32(0.01)
epoch_count = np.int64(100)

print(f"Learning Rate: {learning_rate} (Type: {type(learning_rate)})")
print(f"Epoch Count: {epoch_count} (Type: {type(epoch_count)})")

Learning Rate: 0.009999999776482582 (Type: <class 'numpy.float32'>)
Epoch Count: 100 (Type: <class 'numpy.int64'>)


In [5]:
# 2. Crating a scalar as a 0-dimensional array
scalar_val = np.array(42)
print(f"Scalar Array: {scalar_val}")
print(f"Dimenstionas (ndim): {scalar_val.ndim}")
print(f"Shape: {scalar_val.shape}")

Scalar Array: 42
Dimenstionas (ndim): 0
Shape: ()


In [6]:
# 3. Basic arithmetic with Numpy scalars
a = np.array(7)
b = np.array(3)

sum_result = a + b
product = a * b

print(f"Addition ({a} + {b}): {sum_result}")
print(f"Multiplication ({a} * {b}): {product}")

Addition (7 + 3): 10
Multiplication (7 * 3): 21


## What is Vector?

In linear algebra, a **vector** is an ordered list or array of numbers (scalars). While a scalar is just a single point, a vector can represent a direction and magnitude in space, or a collection of features describing a single data point in machine learning.

- **Geometric View**: An arrow pointing from the origin to a specific point in a multi-dimensional coordinate space.
- **Machine Learning View**: A feature vector representing an entity (e.g., a row of numerical attributes representing a user, or an embedding generated by an AI model capturing semantic meaning).

**Notation and Structure**
- **Notation**: Represented as lowercase bold letters (e.g., $\mathbf{x}$, $\mathbf{v}$).
- **Components**: Written as a column or row of numbers:
$$\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}$$
- **Dimensions**: Unlike scalars (0 dimensions), vectors have 1 dimension and are defined by their length (the number of elements they contain).

In Numpy, vectors are typically implemented using 1-dimensional NumPy arrays.

In [7]:
# 1. Creating a vector (representing a data point with 3 features)
# e.g., [age, income_score, activity_score]
features = np.array([25.0, 54000.0, 8.5])

print(f"Vecotr: {features}")
print(f"Dimensions (ndim): {features.ndim}")
print(f"Shape: {features.shape}")

Vecotr: [2.5e+01 5.4e+04 8.5e+00]
Dimensions (ndim): 1
Shape: (3,)


In [8]:
# 2. Vecotr Arithmetic (Element-wise addition)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

sum_vector = v1 + v2

print(f"Vector Addition ([1,2,3] + [4,5,6]): {sum_vector}")

Vector Addition ([1,2,3] + [4,5,6]): [5 7 9]


In [9]:
# 3. Scalar Multiplication (Scaling a vector)
scaling_factor = 2.5
scaled_vector = v1 * scaling_factor
print(f"Scaled Vector (2.5 * [1,2,3]): {scaled_vector}")

Scaled Vector (2.5 * [1,2,3]): [2.5 5.  7.5]


In [10]:
# 4. Dot Product (Crucial for similarity searches and neural networks)
dot_product = np.dot(v1, v2) # (1*4 + 2*5 + 3*6)
print(f"Dot Product: {dot_product}")

Dot Product: 32


**Why Vectors Matter in Machine Learning**

- **Embeddings**: Text, images, and audio are converted into dense numerical vectors (embeddings) so models can compute semantic similarity (often via vector databases like ChromaDB or FAISS).
- **Feature Representation**: Every sample in a dataset is processed as an input vector before passing through weight matrices in a neural network.

## What is Matrix?

In linear algebra, a matrix is a rectangular grid or array of numbers (scalars) arranged in rows and columns. While a scalar is a single point and a vector is a single line of numbers, a matrix is a 2-dimensional grid.

- **Mathematical View**: A structure defined by its dimensions $m \times n$, where $m$ represents the number of rows and $n$ represents the number of columns.
- **Machine Learning View**: Matrices are used to represent datasets (rows as samples, columns as features), linear transformations, and weights in neural network layers that map inputs to outputs.

**Notation and Structure**
- **Notation**: Represented as uppercase bold letters (e.g., $\mathbf{A}$, $\mathbf{W}$, $\mathbf{X}$).
- **Elements**: Individual entries are indexed by their row and column, denoted as $a_{i,j}$ (row $i$, column $j$).
- **Dimensions**: A matrix with 3 rows and 4 columns has a shape of $3 \times 4$.

In Numpy, matrices are implemented using 2-dimensional NumPy arrays (`ndim == 2`).

In [ ]:
# 1. Creating a 2D matrix (e.g., a neural network weight matrix: 2 inputs, 3 neurons)
weights = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6]
])
print(f"Matrix:\n{weights}")
print(f"Dimensions (ndim): {weights.ndim}")
print(f"Shape: {weights.shape}")

Matrix:
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
Dimensions (ndim): 2
Shape: (2, 3)


In [16]:
# 2. Transposing a matrix (flipping rows and columns)
transpoed_weights = weights.T
print(f"Transposed Matrix Shape: {transpoed_weights.shape}")

Transposed Matrix Shape: (3, 2)


In [18]:
# 3. Matrix Multiplication (Dot product)
# Multiplying a vector (1D array) by a matrix
vector = np.array([1.0, 2.0])
# Using the '@' operator for matrix multiplication
output = vector @ weights
print(f"Matrix-Vector Multiplication Output: {output}")

Matrix-Vector Multiplication Output: [0.9 1.2 1.5]


**Why Matrices Matter in Machine Learning**

- **Neural Network Layers**: A dense (fully connected) layer performs matrix multiplication between an input vector and a weight matrix, followed by adding a bias vector.
- **Batch Processing**: Instead of processing single data vectors one at a time, machine learning frameworks group data into 2D matrices (batches) to harness hardware acceleration (GPUs).

## Core Matrix Operations

### 1. Dot Product

Multiplies corresponding elements and sums them up. For vectors $\mathbf{u} = [1, 2]$ and $\mathbf{v} = [3, 4]$, the dot product is $(1 \times 3) + (2 \times 4) = 11$ (in NumPy: np.dot(u, v)).

In [ ]:
# Multiplies corresponding elements of two vectors and sums the result
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

dot_prod = np.dot(u, v) # (1*4 + 2*5 + 3*6)
print(f"Dot Produt; {dot_product}")

Dot Produt; 32


### 2. Matrix Multiplication

 Combines rows and columns following the rule that the inner dimensions must match. Multiplying an $(m \times n)$ matrix by an $(n \times p)$ matrix results in an $(m \times p)$ matrix using the @ operator.

In [22]:
# Combines rows and columns following inner dimension matching rules
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

matmul_result = A @ B # Or np.matmul(A, B)
print("Matrix Multiplication (A @ B):\n", matmul_result)

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]


### 3. Transpose  ($A^T$)

Flips a matrix across its main diagonal, turning rows into columns. For example, transposing $A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ yields $A^T = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}$.

In [23]:
# Swaps the rows and columns of a matrix
A = np.array([
    [1, 2],
    [3, 4]
])

print("Transposed Matrix (A.T):\n", A.T)

Transposed Matrix (A.T):
 [[1 3]
 [2 4]]


## Advanced Transformations

### Inverse ($A^{-1}$)

A special matrix that "undoes" the original matrix $A$, resulting in the identity matrix when multiplied ($A \cdot A^{-1} = I$). Calculated in Python via `np.linalg.inv(A)`.

The inverse of the matrix $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ is **$\begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}$**.

**Step-by-Step Calculation**

For a general $2 \times 2$ matrix $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$, the inverse is calculated using the formula:
$$A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

**1. Find the Determinant ($\det(A)$)**:
$$\det(A) = (a \times d) - (b \times c)$$
$$\det(A) = (1 \times 4) - (2 \times 3) = 4 - 6 = -2$$

**2. Find the Adjoint Matrix** (Swap $a$ and $d$, change signs of $b$ and $c$):
$$\begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix}$$

**3. Multiply by $1/\det(A)$**:
$$A^{-1} = \frac{1}{-2} \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \begin{bmatrix} \frac{4}{-2} & \frac{-2}{-2} \\ \frac{-3}{-2} & \frac{1}{-2} \end{bmatrix} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}$$


In [25]:
# The inverse of a matrix A undoes its transformation (A * A_inv = Identity)
A = np.array([
    [1, 2],
    [3, 4]
])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)
# Verify by multiplying A by its inverse (should yield an Identity matrix)
identity_check = A @ A_inv
print("Verification (A @ A_inv):\n", np.round(identity_check))

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verification (A @ A_inv):
 [[1. 0.]
 [0. 1.]]


### Eigenvalues ($\lambda$)

Scalars that quantify how much an eigenvector is stretched, compressed, or flipped during a linear transformation.

The eigenvalues for the matrix $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ are found using the formula **$\lambda = \frac{5 \pm \sqrt{33}}{2}$**. 

**Step-by-Step Formula Derivation**

To find the eigenvalues ($\lambda$), you solve the **characteristic equation**:
$$\det(A - \lambda I) = 0$$

**1. Set up the matrix $(A - \lambda I)$**:
$$A - \lambda I = \begin{bmatrix} 1-\lambda & 2 \\ 3 & 4-\lambda \end{bmatrix}$$

**2. Find the determinant**:
$$\det\begin{bmatrix} 1-\lambda & 2 \\ 3 & 4-\lambda \end{bmatrix} = (1-\lambda)(4-\lambda) - (2 \times 3)$$
$$= \lambda^2 - 5\lambda + 4 - 6$$
$$= \lambda^2 - 5\lambda - 2 = 0$$

**3. Apply the quadratic formula**:
For a quadratic equation $a\lambda^2 + b\lambda + c = 0$, the formula is:
$$\lambda = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$

Substitute $a = 1$, $b = -5$, and $c = -2$:
$$\lambda = \frac{-(-5) \pm \sqrt{(-5)^2 - 4(1)(-2)}}{2(1)}$$
$$\lambda = \frac{5 \pm \sqrt{25 + 8}}{2} = \frac{5 \pm \sqrt{33}}{2}$$

* **$\lambda_1 \approx 5.37$**
* **$\lambda_2 \approx -0.37$**


In [26]:
# Eigenvalues are the scaling factors by which they stretch or shrink.
A = np.array([
    [1, 2],
    [3, 4]
])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [-0.37228132+0.j  5.37228132+0.j]


### Eigenvectors

Special non-zero vectors whose direction remains completely unchanged when a linear transformation matrix is applied to them—they only scale by their eigenvalue factor.

Here is the step-by-step calculation to find the **eigenvectors** for the matrix $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ based on the eigenvalues: $\lambda_1 = \frac{5 + \sqrt{33}}{2}$ and $\lambda_2 = \frac{5 - \sqrt{33}}{2}$.

**Step-by-Step Calculation**

To find the eigenvector $\mathbf{v}$ for each eigenvalue $\lambda$, we solve the linear system:
$$(A - \lambda I)\mathbf{v} = \mathbf{0}$$

$$\begin{bmatrix} 1 - \lambda & 2 \\ 3 & 4 - \lambda \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix}$$

---

**1. For $\lambda_1 = \frac{5 + \sqrt{33}}{2} \approx 5.37$**

Substitute $\lambda_1$ into the first row equation $(1 - \lambda)x + 2y = 0$:
$$\left(1 - \frac{5 + \sqrt{33}}{2}\right)x + 2y = 0$$

$$\left(\frac{-3 - \sqrt{33}}{2}\right)x + 2y = 0$$

Now, solve for $y$ in terms of $x$:
$$2y = \left(\frac{3 + \sqrt{33}}{2}\right)x \implies y = \left(\frac{3 + \sqrt{33}}{4}\right)x$$

Setting $x = 4$ to clear the denominator gives the first eigenvector $\mathbf{v}_1$:
$$\mathbf{v}_1 = \begin{bmatrix} 4 \\ 3 + \sqrt{33} \end{bmatrix} \approx \begin{bmatrix} 4 \\ 8.74 \end{bmatrix}$$

---

**2. For $\lambda_2 = \frac{5 - \sqrt{33}}{2} \approx -0.37$**

Substitute $\lambda_2$ into the first row equation $(1 - \lambda)x + 2y = 0$:
$$\left(1 - \frac{5 - \sqrt{33}}{2}\right)x + 2y = 0$$

$$\left(\frac{-3 + \sqrt{33}}{2}\right)x + 2y = 0$$

Now, solve for $y$ in terms of $x$:
$$2y = \left(\frac{3 - \sqrt{33}}{2}\right)x \implies y = \left(\frac{3 - \sqrt{33}}{4}\right)x$$

Setting $x = 4$ to clear the denominator gives the second eigenvector $\mathbf{v}_2$:
$$\mathbf{v}_2 = \begin{bmatrix} 4 \\ 3 - \sqrt{33} \end{bmatrix} \approx \begin{bmatrix} 4 \\ -2.74 \end{bmatrix}$$


In [27]:
# Eigenvectors keep their direction during a linear transformation;
A = np.array([
    [1, 2],
    [3, 4]
])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvectors:\n", eigenvectors)

Eigenvectors:
 [[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


## Spaces & Structure

### 1. Vector Spaces

A mathematical collection of vectors that can be added together and scaled by numbers while following standard algebraic rules (e.g., the standard 2D Cartesian plane $\mathbb{R}^2$).

In [28]:
# A vector space is a collection of vectors that can be scaled and added together.
# In NumPy, a standard 2D vector space (R^2) is represented by any 2-element arrays.
v1 = np.array([1, 0])  # Basis vector i
v2 = np.array([0, 1])  # Basis vector j
linear_combination = 3 * v1 + 2 * v2  # Result stays within the same vector space
print("Linear Combination in R^2:", linear_combination)

Linear Combination in R^2: [3 2]


### Dimensionality

The count of independent directions or features required to specify a point. A dataset where each sample has 5 numerical features has a dimensionality of 5.

In [29]:
# Dimensionality refers to the shape and number of axes (ndim) of an array
data_vector = np.array([1.5, 2.0, 3.5])
print("Vector Shape:", data_vector.shape)  # (3,) -> 1D vector
print("Vector Dimensions (ndim):", data_vector.ndim)  # 1

matrix_2d = np.array([[1, 2], [3, 4]])
print("Matrix Shape:", matrix_2d.shape)  # (2, 2) -> 2D matrix
print("Matrix Dimensions (ndim):", matrix_2d.ndim)  # 2

Vector Shape: (3,)
Vector Dimensions (ndim): 1
Matrix Shape: (2, 2)
Matrix Dimensions (ndim): 2
